CREATE TABLE IF NOT EXISTS event(
  id VARCHAR(255) NOT NULL PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS users(
    id VARCHAR(255) NOT NULL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    image_url VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS user_event(
  user_id VARCHAR(255) NOT NULL,
  event_id VARCHAR(255) NOT NULL,
  payment_status TINYINT NOT NULL,
  fixed_payment INT,
  PRIMARY KEY(user_id, event_id),
  FOREIGN KEY(event_id) REFERENCES event(id)
);

CREATE TABLE IF NOT EXISTS event_payment(
  id VARCHAR(255) NOT NULL PRIMARY KEY,
  event_id VARCHAR(255) NOT NULL,
  amount INT NOT NULL,
  claimant_id VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY(claimant_id) REFERENCES users(user_id),
  FOREIGN KEY(event_id) REFERENCES event(id)
);
